#config server.port
server:
  port: 8080
# config dataSource
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/x?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:
#config mybatis
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.qf.j1904.pojo
